version: '3.7'

services:

  application:
    image: application-image
    container_name: application
    depends_on:
      - postgres
    build:
      context: .
    networks:
      - cloud
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty009
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


  postgres:
    image: 'postgres'
    container_name: database
    networks:
      - cloud
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty009
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  pgdata:
    external: false

networks:
  cloud:
    external: false
